table Donut_Dimensions
	lineageTag: 0b57926e-2dd2-4e08-b275-55b31d974c12

	column 'Driver Name'
		dataType: string
		lineageTag: f95cfae7-50dd-4c4f-aea1-4c9f36844fe5
		summarizeBy: none
		sourceColumn: Driver Name
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 0dd4811b-5f55-4cfa-b802-176376e39f0f
		summarizeBy: sum
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition Donut_Dimensions = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcvQPUwgoyk/LLFHwyUwrUdJRMlSK1YlWcs4oLcpDkzGCyOTnlaUWFWfmo0sbK8XGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Driver Name" = _t, #"Sort Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Driver Name", type text}, {"Sort Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

